use deimos_db;

# Seed owners

insert into owners (name, address) values ('Cristina', '84856 Morrow Road');
insert into owners (name, address) values ('Patti', '8400 Kinsman Circle');
insert into owners (name, address) values ('Inger', '5643 Merrick Pass');
insert into owners (name, address) values ('Sidney', '332 Russell Plaza');
insert into owners (name, address) values ('Johnathon', '35749 Talisman Hill');
insert into owners (name, address) values ('Myrvyn', '1 Spaight Hill');
insert into owners (name, address) values ('Sherline', '0 American Ash Drive');
insert into owners (name, address) values ('Hector', '56 Forest Hill');
insert into owners (name, address) values ('Whitaker', '30024 Lawn Hill');
insert into owners (name, address) values ('Glen', '194 South Center');
insert into owners (name, address) values ('Baxy', '4 Sundown Trail');
insert into owners (name, address) values ('Teddi', '811 Merchant Trail');
insert into owners (name, address) values ('Damien', '72 Park Meadow Alley');
insert into owners (name, address) values ('Rosa', '6 Schurz Hill');
insert into owners (name, address) values ('Liv', '810 Vahlen Hill');
insert into owners (name, address) values ('Dorella', '22520 Comanche Road');
insert into owners (name, address) values ('Margery', '8 Ridge Oak Plaza');
insert into owners (name, address) values ('Marleah', '84 Emmet Alley');
insert into owners (name, address) values ('Pedro', '51375 Gale Junction');
insert into owners (name, address) values ('Clementius', '559 Veith Way');
insert into owners (name, address) values ('Deane', '6 Northridge Trail');
insert into owners (name, address) values ('Bruis', '571 Bellgrove Avenue');
insert into owners (name, address) values ('Susanetta', '04895 Holmberg Plaza');
insert into owners (name, address) values ('Cris', '7972 Pearson Court');
insert into owners (name, address) values ('Stephanie', '0 Waxwing Crossing');
insert into owners (name, address) values ('Caitlin', '230 Arkansas Hill');
insert into owners (name, address) values ('Karia', '45710 Fisk Point');
insert into owners (name, address) values ('Stephanie', '5396 Little Fleur Trail');
insert into owners (name, address) values ('Michele', '29474 Namekagon Center');
insert into owners (name, address) values ('Raquel', '780 Crescent Oaks Crossing');
insert into owners (name, address) values ('Wilhelm', '84 Dexter Park');
insert into owners (name, address) values ('David', '79 Vahlen Pass');
insert into owners (name, address) values ('Buiron', '3 1st Road');
insert into owners (name, address) values ('Ray', '976 2nd Street');
insert into owners (name, address) values ('Edan', '0 Merrick Junction');
insert into owners (name, address) values ('Carey', '014 Hoepker Center');
insert into owners (name, address) values ('Melitta', '60 Buhler Park');
insert into owners (name, address) values ('Layne', '2 Carpenter Crossing');
insert into owners (name, address) values ('Jayme', '7310 Dapin Park');
insert into owners (name, address) values ('Gwenni', '5018 Laurel Pass');
insert into owners (name, address) values ('Suellen', '09 Pleasure Terrace');
insert into owners (name, address) values ('Daphna', '44377 Truax Park');
insert into owners (name, address) values ('Elmo', '00025 Tennessee Place');
insert into owners (name, address) values ('Harriett', '0118 Bunker Hill Crossing');
insert into owners (name, address) values ('Marmaduke', '505 Del Mar Drive');
insert into owners (name, address) values ('Faustina', '572 Oak Valley Road');
insert into owners (name, address) values ('Kalli', '636 Sherman Trail');
insert into owners (name, address) values ('Avictor', '7 Claremont Crossing');
insert into owners (name, address) values ('Merrel', '06 Scott Junction');
insert into owners (name, address) values ('Merv', '7250 Pawling Park');
insert into owners (name, address) values ('Nicola', '59330 Buhler Lane');
insert into owners (name, address) values ('Reta', '17 Sundown Pass');
insert into owners (name, address) values ('Fredrika', '68107 Superior Way');
insert into owners (name, address) values ('Natalina', '1 Raven Court');
insert into owners (name, address) values ('Ariela', '45 Forest Plaza');
insert into owners (name, address) values ('Berri', '8 Badeau Hill');
insert into owners (name, address) values ('Sterne', '13 Lillian Point');
insert into owners (name, address) values ('Caressa', '90379 Maple Wood Hill');
insert into owners (name, address) values ('Kit', '8559 Continental Place');
insert into owners (name, address) values ('Florette', '73 Heath Hill');
insert into owners (name, address) values ('Loralyn', '52 Anderson Crossing');
insert into owners (name, address) values ('Hanna', '38354 New Castle Center');
insert into owners (name, address) values ('Ellery', '7 Packers Road');
insert into owners (name, address) values ('Tobye', '93426 East Lane');
insert into owners (name, address) values ('Isa', '29 Carberry Park');
insert into owners (name, address) values ('Kate', '04128 Anthes Street');
insert into owners (name, address) values ('Kinnie', '1 Arkansas Place');
insert into owners (name, address) values ('Sib', '63 Grover Street');
insert into owners (name, address) values ('Berkie', '06308 Weeping Birch Drive');
insert into owners (name, address) values ('Lindon', '298 Grayhawk Place');
insert into owners (name, address) values ('Adriaens', '9 Bartelt Avenue');
insert into owners (name, address) values ('Cleon', '84 7th Parkway');
insert into owners (name, address) values ('Allsun', '1 Lyons Plaza');
insert into owners (name, address) values ('Clemens', '65 Columbus Junction');
insert into owners (name, address) values ('Yardley', '779 Duke Court');
insert into owners (name, address) values ('Tedie', '44 Express Court');
insert into owners (name, address) values ('Waylen', '939 Cordelia Circle');
insert into owners (name, address) values ('Leonid', '949 Declaration Point');
insert into owners (name, address) values ('Brewster', '7116 Dapin Court');
insert into owners (name, address) values ('Dael', '59 Carpenter Parkway');
insert into owners (name, address) values ('Heda', '86 Manley Crossing');
insert into owners (name, address) values ('Giovanna', '491 Eggendart Center');
insert into owners (name, address) values ('Roshelle', '28763 Hollow Ridge Place');
insert into owners (name, address) values ('Tabb', '7869 Butternut Point');
insert into owners (name, address) values ('Carolyne', '2 Fair Oaks Lane');
insert into owners (name, address) values ('Louise', '25975 Thackeray Lane');
insert into owners (name, address) values ('Lawrence', '12 Mesta Avenue');
insert into owners (name, address) values ('Caryl', '12015 Pleasure Hill');
insert into owners (name, address) values ('Alejandro', '439 Spohn Lane');
insert into owners (name, address) values ('Brittan', '7 Forster Place');
insert into owners (name, address) values ('Dodie', '0466 Valley Edge Point');
insert into owners (name, address) values ('Parry', '1864 Hanson Point');
insert into owners (name, address) values ('Cecilia', '3 Crownhardt Point');
insert into owners (name, address) values ('Siffre', '0907 Mandrake Center');
insert into owners (name, address) values ('Neil', '48760 Twin Pines Park');
insert into owners (name, address) values ('Antoinette', '298 Eliot Road');
insert into owners (name, address) values ('Melli', '3 Norway Maple Point');
insert into owners (name, address) values ('Lalo', '384 Sycamore Drive');
insert into owners (name, address) values ('Ripley', '77487 Lillian Junction');
insert into owners (name, address) values ('Gerladina', '60173 Melody Court');


# Seed pets

insert into pets (name, owner_id, age) values ('Karry', 100, 6);
insert into pets (name, owner_id, age) values ('Bailey', 39, 4);
insert into pets (name, owner_id, age) values ('Silva', 90, 8);
insert into pets (name, owner_id, age) values ('Emili', 70, 1);
insert into pets (name, owner_id, age) values ('Herve', 25, 6);
insert into pets (name, owner_id, age) values ('Idette', 26, 5);
insert into pets (name, owner_id, age) values ('Inglis', 46, 1);
insert into pets (name, owner_id, age) values ('Lynea', 40, 2);
insert into pets (name, owner_id, age) values ('Witty', 76, 5);
insert into pets (name, owner_id, age) values ('Hobart', 26, 5);
insert into pets (name, owner_id, age) values ('Shamus', 54, 2);
insert into pets (name, owner_id, age) values ('Curtis', 54, 8);
insert into pets (name, owner_id, age) values ('Prentiss', 69, 7);
insert into pets (name, owner_id, age) values ('Chevy', 54, 9);
insert into pets (name, owner_id, age) values ('Ambros', 69, 8);
insert into pets (name, owner_id, age) values ('Johnette', 94, 8);
insert into pets (name, owner_id, age) values ('Jack', 50, 4);
insert into pets (name, owner_id, age) values ('Eva', 94, 6);
insert into pets (name, owner_id, age) values ('Britney', 8, 5);
insert into pets (name, owner_id, age) values ('Brandy', 32, 7);
insert into pets (name, owner_id, age) values ('Farrel', 2, 1);
insert into pets (name, owner_id, age) values ('Jaynell', 12, 3);
insert into pets (name, owner_id, age) values ('Corby', 50, 9);
insert into pets (name, owner_id, age) values ('Dall', 74, 2);
insert into pets (name, owner_id, age) values ('Matthaeus', 70, 6);
insert into pets (name, owner_id, age) values ('Isiahi', 9, 6);
insert into pets (name, owner_id, age) values ('Glyn', 8, 10);
insert into pets (name, owner_id, age) values ('Jorgan', 27, 5);
insert into pets (name, owner_id, age) values ('Yves', 36, 10);
insert into pets (name, owner_id, age) values ('Calli', 77, 8);
insert into pets (name, owner_id, age) values ('Ida', 53, 9);
insert into pets (name, owner_id, age) values ('Bax', 7, 1);
insert into pets (name, owner_id, age) values ('Goddard', 54, 10);
insert into pets (name, owner_id, age) values ('Henriette', 72, 4);
insert into pets (name, owner_id, age) values ('Fifine', 51, 2);
insert into pets (name, owner_id, age) values ('Natka', 53, 6);
insert into pets (name, owner_id, age) values ('Angela', 81, 9);
insert into pets (name, owner_id, age) values ('Shellysheldon', 10, 6);
insert into pets (name, owner_id, age) values ('Naoma', 56, 10);
insert into pets (name, owner_id, age) values ('Sanford', 14, 1);
insert into pets (name, owner_id, age) values ('Rosamond', 30, 3);
insert into pets (name, owner_id, age) values ('Randy', 17, 2);
insert into pets (name, owner_id, age) values ('Christin', 28, 7);
insert into pets (name, owner_id, age) values ('Mathilda', 31, 1);
insert into pets (name, owner_id, age) values ('Pablo', 4, 10);
insert into pets (name, owner_id, age) values ('Benn', 6, 5);
insert into pets (name, owner_id, age) values ('Lotti', 87, 10);
insert into pets (name, owner_id, age) values ('Aleksandr', 68, 7);
insert into pets (name, owner_id, age) values ('Eleonore', 19, 4);
insert into pets (name, owner_id, age) values ('Marius', 77, 8);
insert into pets (name, owner_id, age) values ('Nelie', 42, 8);
insert into pets (name, owner_id, age) values ('Mylo', 28, 7);
insert into pets (name, owner_id, age) values ('Arturo', 77, 10);
insert into pets (name, owner_id, age) values ('Dan', 5, 8);
insert into pets (name, owner_id, age) values ('Amalle', 89, 5);
insert into pets (name, owner_id, age) values ('Ange', 73, 6);
insert into pets (name, owner_id, age) values ('Inna', 64, 1);
insert into pets (name, owner_id, age) values ('Atlanta', 4, 3);
insert into pets (name, owner_id, age) values ('Maurits', 51, 4);
insert into pets (name, owner_id, age) values ('Dennie', 31, 3);
insert into pets (name, owner_id, age) values ('Danit', 95, 5);
insert into pets (name, owner_id, age) values ('Alwyn', 88, 8);
insert into pets (name, owner_id, age) values ('Amos', 15, 9);
insert into pets (name, owner_id, age) values ('Murray', 73, 8);
insert into pets (name, owner_id, age) values ('Ingeborg', 46, 5);
insert into pets (name, owner_id, age) values ('Tristam', 70, 4);
insert into pets (name, owner_id, age) values ('Maxy', 27, 4);
insert into pets (name, owner_id, age) values ('Linus', 71, 4);
insert into pets (name, owner_id, age) values ('Marlon', 39, 10);
insert into pets (name, owner_id, age) values ('Hermon', 15, 6);
insert into pets (name, owner_id, age) values ('Staford', 30, 5);
insert into pets (name, owner_id, age) values ('Dulci', 64, 3);
insert into pets (name, owner_id, age) values ('Cort', 16, 3);
insert into pets (name, owner_id, age) values ('Eyde', 51, 2);
insert into pets (name, owner_id, age) values ('Eugenio', 18, 2);
insert into pets (name, owner_id, age) values ('Dennis', 95, 5);
insert into pets (name, owner_id, age) values ('Therese', 58, 7);
insert into pets (name, owner_id, age) values ('Inez', 86, 10);
insert into pets (name, owner_id, age) values ('Babb', 100, 1);
insert into pets (name, owner_id, age) values ('Nikki', 57, 9);
insert into pets (name, owner_id, age) values ('Guinevere', 71, 7);
insert into pets (name, owner_id, age) values ('Barris', 67, 7);
insert into pets (name, owner_id, age) values ('Viki', 7, 8);
insert into pets (name, owner_id, age) values ('Valera', 55, 8);
insert into pets (name, owner_id, age) values ('Adolph', 69, 7);
insert into pets (name, owner_id, age) values ('Hortensia', 24, 8);
insert into pets (name, owner_id, age) values ('Levy', 19, 8);
insert into pets (name, owner_id, age) values ('Aileen', 3, 7);
insert into pets (name, owner_id, age) values ('Ansley', 95, 10);
insert into pets (name, owner_id, age) values ('Celestyna', 19, 4);
insert into pets (name, owner_id, age) values ('Vaclav', 14, 2);
insert into pets (name, owner_id, age) values ('Yurik', 37, 5);
insert into pets (name, owner_id, age) values ('Tobiah', 84, 6);
insert into pets (name, owner_id, age) values ('Hugh', 30, 6);
insert into pets (name, owner_id, age) values ('Monah', 22, 4);
insert into pets (name, owner_id, age) values ('Correy', 66, 3);
insert into pets (name, owner_id, age) values ('Mignon', 68, 7);
insert into pets (name, owner_id, age) values ('Benetta', 23, 1);
insert into pets (name, owner_id, age) values ('Butch', 33, 7);
insert into pets (name, owner_id, age) values ('Nara', 17, 6);

